In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [2]:
import tensorflow
from tensorflow.keras.models import load_model

In [3]:
model=load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [4]:
### load one hot encoder and label encoder,standard scaler
with open("one_hot_encoder_geo.pkl",'rb') as file:
    one_hot_encoder_geo=pickle.load(file)
with open("lbl_encoder.pkl",'rb') as file:
    ldl_encoder=pickle.load(file)
with open("scaler.pkl",'rb') as file:
    scaler=pickle.load(file)

In [5]:
### take one input
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

### convert the Geography column by one hot encoder

In [6]:
encoded_geo=one_hot_encoder_geo.transform([[input_data['Geography']]]).toarray()
encoded_df_geo=pd.DataFrame(encoded_geo,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
encoded_df_geo

e:\DL_project1\ANN_classification\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [7]:
### first convert the input data to dataframe
input_df=pd.DataFrame([input_data])

In [8]:
input_df['Gender']=ldl_encoder.transform(input_df['Gender'])

In [9]:
### concatenate of two dataframe
input_df=pd.concat([input_df,encoded_df_geo],axis=1)

In [10]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

#### drop the geography columns

In [11]:
input_df=input_df.drop('Geography',axis=1)

In [12]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [13]:
### Apply standard scaler
input_scale=scaler.transform(input_df)

In [14]:
input_scale

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [16]:
prediction=model.predict(input_scale)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

array([[0.02772924]], dtype=float32)

In [19]:
prediction_prob=prediction[0][0]
prediction_prob

np.float32(0.027729236)

In [20]:
if prediction_prob>0.5:
    print("customer likely to churn")
else:
    print("customer is not likely to churn")

customer is not likely to churn